name: Build Course
on:
  workflow_dispatch:
    inputs:
      course_code:
        description: Code of the course to build
        required: true
        type: string
      course_description:
        description: Description of the course to build
        required: true
        type: string

concurrency: dscourses-writer

jobs:
  build_course:
    runs-on: ubuntu-latest
    steps:
      - id: course-code
        run: course_code=${{ inputs.course_code }} ; echo lowercase=${course_code,,} >> "$GITHUB_OUTPUT"

      - name: Checkout pipelines repository
        uses: actions/checkout@v2

      - name: Get active branch
        id: active-branch
        run: |
          course_code=${{ steps.course-code.outputs.lowercase }}
          echo active-branch=$(jq -r 'if has("$course_code") then .$course_code else "" end' ./branches.json) >> "$GITHUB_OUTPUT"

      - name: Checkout ${{ inputs.course_code }} repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.course_code }}
          path: docs
          ref: ${{ steps.active-branch.outputs.active-branch }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Checkout dscourses repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/dscourses
          path: dscourses
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get current year
        id: current-year
        run: echo "current-year=$(date +%Y)" >> "$GITHUB_OUTPUT"

      - name: Generate PDF name
        id: pdf-name
        run: |
          shopt -s extglob
          result=${{ inputs.course_code }} ; result="${result,,}" ; echo result="${result//+([[:space:]])/-}.pdf" >> "$GITHUB_OUTPUT"

      - name: Generate MkDocs Configuration
        shell: sh
        run: |
          cat > mkdocs.yml <<EOF
          site_name: '${{ inputs.course_code }}'
          site_url: https://www.deso.tech
          site_description: '${{ inputs.course_description }}'
          site_author: Desotech TM
          copyright: Copyright &copy; 2016 - ${{ steps.current-year.outputs.current-year }} Desotech
          use_directory_urls: false
          theme:
            name: null
            custom_dir: material
            highlightjs: true
            hljs_languages:
              - yaml
            features:
              - header.autohide
              - toc.integrate
            include_sidebar: true
            static_templates:
              - 404.html
            include_search_page: false
            search_index_only: true
            language: en
            feature:
              tabs: false
            palette:
              primary: grey
              accent: grey
            font:
              text: Roboto
              code: Roboto Mono
            favicon: assets/favicon.ico
            logo: assets/desotech-cubo-small.png
          markdown_extensions:
            - admonition
            - abbr
            - attr_list
            - def_list
            - footnotes
            - meta
            - toc:
                permalink: true
            - pymdownx.arithmatex:
                generic: true
            - pymdownx.betterem:
                smart_enable: all
            - pymdownx.caret
            - pymdownx.critic
            - pymdownx.details
            - pymdownx.emoji:
                emoji_index: !!python/name:materialx.emoji.twemoji
                emoji_generator: !!python/name:materialx.emoji.to_svg
            - pymdownx.highlight
            - pymdownx.inlinehilite
            - pymdownx.keys
            - pymdownx.mark
            - pymdownx.smartsymbols
            - pymdownx.snippets:
                check_paths: true
            - pymdownx.superfences:
                custom_fences:
                  - name: mermaid
                    class: mermaid
                    format: !!python/name:pymdownx.superfences.fence_code_format
            - pymdownx.tabbed
            - pymdownx.tasklist:
                custom_checkbox: true
            - pymdownx.tilde
          plugins:
            - minify:
                minify_html: false
            - codeinclude
            - awesome-pages
            - img2fig
            - exclude:
                glob:
                  - mkdocs.yml
                  - '*.incomplete'
                  - 'drafts/*'
            - with-pdf:
                author: Desotech srl
                copyright: ${{ steps.year.outputs.year }} Desotech srl or its affiliates. All rights reserved.
                cover_logo: assets/logopdf.png
                cover: true
                back_cover: true
                cover_subtitle: '${{ inputs.course_description }}'
                ordered_chapter_level: 2
                render_js: true
                headless_chrome_path: chrome
                output_path: 'pdf/${{ steps.pdf-name.outputs.result }}'
                debug_html: false
                show_anchors: false
                verbose: false
          EOF

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set Up Chromium
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: '848897'

      - name: Install Python Dependencies
        shell: sh
        run: |
          set -eu
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Link assets folder
        shell: sh
        run: ln -fs ../assets docs/assets

      - name: Build Site
        shell: sh
        run: mkdocs build

      - name: Add Favicon
        run: base64 -d > site/favicon.ico <<< 'AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAABILAAASCwAAAAAAAAAAAAD//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////v///v7////////////////////////////////////////////////////////////////////////+/v/+/v7///////79/f/////////////////////////////////29vb/8PDw/+7u7v/s7Oz/7Ozs/+vq6v/v8PH/8PHx/+zr6v/3+vz/7Ozr/+vq5//s6+j/7e3t//Dw8P/29vX/9fX1/+/v7//s7Oz/6urq/+jo6P/q6+z/4+De/31eN/9pRhL/qZd//+zu8v/r8P//7fH9/+zt7//v7u7/9PT0///////////////////////9/Pv//////7Khif9WLwD/Z0ID/1cvAf/Zy63/9Nh3/+7Wh//+/PT//////////v///////////////////////fz7//////+8pYf/XSwA/2I8AP9xUyL/27hG/9ymAP/XoAD/7dWA///////+/fv////////////+//////////7+/v//////1e7m/5qef/93TBf/gWIy//HIM//cqQD/2qcA//HdmP////////77///////+//7///////z+/f//////1fDo/zW7lf87zaz/bcWp/3hTJf+ujDH/4rYa/+CxDf/69eT////////+/f///////v/+//f8+//9//7//////3LRt/8it47/KbSL/0jPsP9/YTH/WTEA/31fLf/dsyL/7tR5//78+P///////////6Lfzv9Cv5z/a8yw/2HOsf9KwJ7/U7iW/0DHpf9hk2//ZzYB/1o2AP9tTiP/3bUr/9qkAP/lwkb///////////9Vxqb/HLGH/yW4kP9OvJz/hGAy/3NLEf9uTh//h2Eq/5Z0Iv+EZCf/wJst/+OwBv/WnwD/6Mlb////////////sOTW/0zAn/8swpv/cqmL/3YvAP9WLgD/ck8i/+jDOv/puAf/5bUM//HUbP/w3Zr/7dR8//z46v////////////7/////////u+nc/0jBoP9qkGr/iHVQ/9TCnv/luBz/05wA/+bEU//////////+//////////7////////////8/v7///////P7+f9BwJ3/JcKb/1PQs//2/f7/+/LX//Tlr//9+e3///////79+v/+/vv////+/////////////v/////////4/fv/Zcuu/yu0jP9kyKr//P38///////////////+/////v//////////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=='

      - name: Copy Output Files
        shell: sh
        run: rsync -r --delete site/ --exclude password.txt --exclude .htpasswd dscourses/${{ steps.string.outputs.lowercase }}

      - name: Push Changes
        run: |
          git -C dscourses config --local user.name 'GitHub Actions'
          git -C dscourses config --local user.email actions@desotech.it
          git -C dscourses add -A
          if git -C dscourses commit -m 'Update ${{ inputs.course_code }}'
          then
            retries=0
            until git -C dscourses push || [ "$retries" -gt 10 ] ; do sleep 5 ; git -C dscourses pull --rebase ; ((retries++)) ; done
          else
            echo 'Nothing to commit. The site is already up-to-date.'
          fi
