name: Update htpasswd file
on:
  workflow_call:
    inputs:
      course_code:
        description: Code of the course to build
        required: true
        type: string
    secrets:
      dscourses_ssh_key:
        required: true

jobs:
  write_htpasswd:
    runs-on: ubuntu-latest
    env:
      DESOTECH_PASSWORD: D3s0t3ch.itD3s0t3ch.it
    steps:
      - name: Checkout dscourses repository
        uses: actions/checkout@v2
        with:
          ssh-key: '${{ secrets.dscourses_ssh_key }}'
          repository: desotech-it/dscourses
          path: dscourses

      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: '${{ inputs.course_code }}'

      - id: generate_password
        run: echo "::set-output name=course_password::$(< /dev/random tr -dc _A-Z-a-z-0-9 | head -c7)"

      - name: Install htpasswd
        run: apt-get update -y && apt-get install -y apache2-utils

      - id: generate_htpasswd
        run: |
          htpasswd -c -b dscourses/${{ steps.string.outputs.lowercase }}/.htpasswd desotech "$DESOTECH_PASSWORD"
          htpasswd -b dscourses/${{ steps.string.outputs.lowercase }}/.htpasswd '${{ steps.string.outputs.lowercase }}' '${{ steps.generate_password.outputs.course_password }}'

      - name: Push Changes
        shell: sh
        run: |
          git -C dscourses config --local user.name 'GitHub Actions'
          git -C dscourses config --local user.email actions@desotech.it
          git -C dscourses add -A
          if git -C dscourses commit -m 'Update htpasswd for ${{ inputs.course_code }}'
          then
            git -C dscourses push
          else
            echo 'Nothing to commit. The site is already up-to-date.'
          fi
